spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=UTF8&serverTimezone=UTC&userSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8083
env:
  test469
    
