spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiezf168/config-repo.git
          username: xiezf168
          password: 136300word
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
