spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?serverTimezone=UTC&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080
        
logging:
  level:
    org.springframework.cloud.openfeign: debug        
        
        
        
        
        
        
        